// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: desktop.proto
// Protobuf C++ Version: 6.33.0

#ifndef desktop_2eproto_2epb_2eh
#define desktop_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "hyprland.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_desktop_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_desktop_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_desktop_2eproto;
}  // extern "C"
class Desktop;
struct DesktopDefaultTypeInternal;
extern DesktopDefaultTypeInternal _Desktop_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Desktop_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class Desktop final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Desktop) */ {
 public:
  inline Desktop() : Desktop(nullptr) {}
  ~Desktop() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Desktop* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Desktop));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Desktop(::google::protobuf::internal::ConstantInitialized);

  inline Desktop(const Desktop& from) : Desktop(nullptr, from) {}
  inline Desktop(Desktop&& from) noexcept
      : Desktop(nullptr, ::std::move(from)) {}
  inline Desktop& operator=(const Desktop& from) {
    CopyFrom(from);
    return *this;
  }
  inline Desktop& operator=(Desktop&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Desktop& default_instance() {
    return *reinterpret_cast<const Desktop*>(
        &_Desktop_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Desktop& a, Desktop& b) { a.Swap(&b); }
  inline void Swap(Desktop* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Desktop* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Desktop* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Desktop>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Desktop& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Desktop& from) { Desktop::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Desktop* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Desktop"; }

  explicit Desktop(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Desktop(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Desktop& from);
  Desktop(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Desktop&& from) noexcept
      : Desktop(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kClientsFieldNumber = 1,
    kActiveWindowFieldNumber = 2,
  };
  // .Clients clients = 1;
  bool has_clients() const;
  void clear_clients() ;
  const ::Clients& clients() const;
  [[nodiscard]] ::Clients* PROTOBUF_NULLABLE release_clients();
  ::Clients* PROTOBUF_NONNULL mutable_clients();
  void set_allocated_clients(::Clients* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_clients(::Clients* PROTOBUF_NULLABLE value);
  ::Clients* PROTOBUF_NULLABLE unsafe_arena_release_clients();

  private:
  const ::Clients& _internal_clients() const;
  ::Clients* PROTOBUF_NONNULL _internal_mutable_clients();

  public:
  // .Client active_window = 2;
  bool has_active_window() const;
  void clear_active_window() ;
  const ::Client& active_window() const;
  [[nodiscard]] ::Client* PROTOBUF_NULLABLE release_active_window();
  ::Client* PROTOBUF_NONNULL mutable_active_window();
  void set_allocated_active_window(::Client* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_active_window(::Client* PROTOBUF_NULLABLE value);
  ::Client* PROTOBUF_NULLABLE unsafe_arena_release_active_window();

  private:
  const ::Client& _internal_active_window() const;
  ::Client* PROTOBUF_NONNULL _internal_mutable_active_window();

  public:
  // @@protoc_insertion_point(class_scope:Desktop)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   2, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Desktop& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::Clients* PROTOBUF_NULLABLE clients_;
    ::Client* PROTOBUF_NULLABLE active_window_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_desktop_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Desktop_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Desktop

// .Clients clients = 1;
inline bool Desktop::has_clients() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  PROTOBUF_ASSUME(!value || _impl_.clients_ != nullptr);
  return value;
}
inline const ::Clients& Desktop::_internal_clients() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Clients* p = _impl_.clients_;
  return p != nullptr ? *p : reinterpret_cast<const ::Clients&>(::_Clients_default_instance_);
}
inline const ::Clients& Desktop::clients() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Desktop.clients)
  return _internal_clients();
}
inline void Desktop::unsafe_arena_set_allocated_clients(
    ::Clients* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.clients_);
  }
  _impl_.clients_ = reinterpret_cast<::Clients*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Desktop.clients)
}
inline ::Clients* PROTOBUF_NULLABLE Desktop::release_clients() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::Clients* released = _impl_.clients_;
  _impl_.clients_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Clients* PROTOBUF_NULLABLE Desktop::unsafe_arena_release_clients() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Desktop.clients)

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::Clients* temp = _impl_.clients_;
  _impl_.clients_ = nullptr;
  return temp;
}
inline ::Clients* PROTOBUF_NONNULL Desktop::_internal_mutable_clients() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.clients_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Clients>(GetArena());
    _impl_.clients_ = reinterpret_cast<::Clients*>(p);
  }
  return _impl_.clients_;
}
inline ::Clients* PROTOBUF_NONNULL Desktop::mutable_clients()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::Clients* _msg = _internal_mutable_clients();
  // @@protoc_insertion_point(field_mutable:Desktop.clients)
  return _msg;
}
inline void Desktop::set_allocated_clients(::Clients* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.clients_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }

  _impl_.clients_ = reinterpret_cast<::Clients*>(value);
  // @@protoc_insertion_point(field_set_allocated:Desktop.clients)
}

// .Client active_window = 2;
inline bool Desktop::has_active_window() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.active_window_ != nullptr);
  return value;
}
inline const ::Client& Desktop::_internal_active_window() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Client* p = _impl_.active_window_;
  return p != nullptr ? *p : reinterpret_cast<const ::Client&>(::_Client_default_instance_);
}
inline const ::Client& Desktop::active_window() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Desktop.active_window)
  return _internal_active_window();
}
inline void Desktop::unsafe_arena_set_allocated_active_window(
    ::Client* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.active_window_);
  }
  _impl_.active_window_ = reinterpret_cast<::Client*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Desktop.active_window)
}
inline ::Client* PROTOBUF_NULLABLE Desktop::release_active_window() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::Client* released = _impl_.active_window_;
  _impl_.active_window_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Client* PROTOBUF_NULLABLE Desktop::unsafe_arena_release_active_window() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Desktop.active_window)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::Client* temp = _impl_.active_window_;
  _impl_.active_window_ = nullptr;
  return temp;
}
inline ::Client* PROTOBUF_NONNULL Desktop::_internal_mutable_active_window() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.active_window_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Client>(GetArena());
    _impl_.active_window_ = reinterpret_cast<::Client*>(p);
  }
  return _impl_.active_window_;
}
inline ::Client* PROTOBUF_NONNULL Desktop::mutable_active_window()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::Client* _msg = _internal_mutable_active_window();
  // @@protoc_insertion_point(field_mutable:Desktop.active_window)
  return _msg;
}
inline void Desktop::set_allocated_active_window(::Client* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.active_window_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.active_window_ = reinterpret_cast<::Client*>(value);
  // @@protoc_insertion_point(field_set_allocated:Desktop.active_window)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // desktop_2eproto_2epb_2eh
